//! JavaScript glue generation.
//!
//! There is no standardised way for Wasm to call a Web API without JavaScript
//! glue — no Web IDL bindings proposal has landed, and none is imminent. Kite
//! therefore declares the host boundary explicitly and *generates* the glue
//! from that declaration, so the two cannot drift apart.
//!
//! The generated module is deliberately tiny and has no dependencies.

/// The JavaScript module that instantiates a compiled Kite program.
pub fn generate_glue(strings: &[String], wasm_path: &str) -> String {
    let table = strings
        .iter()
        .map(|s| format!("  {},", json_string(s)))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// Generated by kitec. Do not edit.
//
// Kite programs reach the host through a declared boundary rather than an
// ambient runtime, so everything the module can do is visible in this file.

// String constants. A `str` is an index into this table, which is why the
// module needs no linear memory. Concatenation appends, so the table grows.
const STRINGS = [
{table}
];

function intern(s) {{
  const existing = STRINGS.indexOf(s);
  if (existing !== -1) return existing;
  return STRINGS.push(s) - 1;
}}

// An `int` is an i64, which reaches here as a BigInt.
const showInt = (v) => String(v);

// Floats print so they read back as Kite floats: `1.0`, not `1`.
const showFloat = (v) =>
  Number.isFinite(v) && Number.isInteger(v) ? v.toFixed(1) : String(v);

const showBool = (v) => (v ? "true" : "false");

/// Where output goes. Replace to capture it.
export let write = (line) => console.log(line);

export function setWriter(fn) {{
  write = fn;
}}

function imports() {{
  return {{
    kite: {{
      print_int: (v) => write(showInt(v)),
      print_float: (v) => write(showFloat(v)),
      print_bool: (v) => write(showBool(v)),
      print_str: (i) => write(STRINGS[i]),
      str_concat: (a, b) => intern(STRINGS[a] + STRINGS[b]),
      str_eq: (a, b) => (STRINGS[a] === STRINGS[b] ? 1 : 0),
      // Interpolation shares its formatting with printing, so a value cannot
      // look one way in `io.print(x)` and another in `"\(x)"`.
      str_of_int: (v) => intern(showInt(v)),
      str_of_float: (v) => intern(showFloat(v)),
      str_of_bool: (v) => intern(showBool(v)),
    }},
  }};
}}

export async function instantiate(source = {wasm}) {{
  const bytes =
    source instanceof Uint8Array
      ? source
      : new Uint8Array(await (await fetch(source)).arrayBuffer());
  const {{ instance }} = await WebAssembly.instantiate(bytes, imports());
  return instance.exports;
}}

export async function run(source) {{
  const exports = await instantiate(source);
  if (typeof exports.main !== "function") {{
    throw new Error("this module has no `main`");
  }}
  return exports.main();
}}
"#,
        table = table,
        wasm = json_string(wasm_path),
    )
}

/// Encode a Rust string as a JavaScript string literal.
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Escape control characters and the line separators that are legal
            // in JSON but not in a JavaScript string literal.
            c if (c as u32) < 0x20 || c == '\u{2028}' || c == '\u{2029}' => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strings_are_escaped_for_javascript() {
        assert_eq!(json_string("a\"b"), r#""a\"b""#);
        assert_eq!(json_string("a\nb"), r#""a\nb""#);
        assert_eq!(json_string("a\\b"), r#""a\\b""#);
        assert_eq!(json_string("tab\there"), r#""tab\there""#);
    }

    /// U+2028 and U+2029 are valid JSON but terminate a JavaScript string
    /// literal, which is a classic way to generate broken glue.
    #[test]
    fn line_separators_are_escaped() {
        assert_eq!(json_string("a\u{2028}b"), "\"a\\u2028b\"");
        assert_eq!(json_string("a\u{2029}b"), "\"a\\u2029b\"");
    }

    #[test]
    fn the_glue_embeds_every_string_constant() {
        let g = generate_glue(&["hello".into(), "world".into()], "app.wasm");
        assert!(g.contains(r#""hello""#));
        assert!(g.contains(r#""world""#));
        assert!(g.contains(r#""app.wasm""#));
        assert!(g.contains("export async function run"));
    }
}
