//! JavaScript glue generation.
//!
//! There is no standardised way for Wasm to call a Web API without JavaScript
//! glue — no Web IDL bindings proposal has landed, and none is imminent. Kite
//! therefore declares the host boundary explicitly and *generates* the glue
//! from that declaration, so the two cannot drift apart.
//!
//! The generated module is deliberately tiny and has no dependencies.

/// The JavaScript module that instantiates a compiled Kite program.
pub fn generate_glue(strings: &[String], wasm_path: &str) -> String {
    generate_glue_with_hosts(strings, wasm_path, &[])
}

/// The glue, including the host groups a program declared.
///
/// Every `@host("group") extern fn` becomes an entry the host must supply.
/// The generated module declares each group as an object a page can fill in
/// with `provide("group", { … })` before running — and a call to something
/// nobody supplied fails saying which declaration it was, rather than doing
/// nothing.
pub fn generate_glue_with_hosts(
    strings: &[String],
    wasm_path: &str,
    hosts: &[crate::HostImport],
) -> String {
    let table = strings
        .iter()
        .map(|s| format!("  {},", json_string(s)))
        .collect::<Vec<_>>()
        .join("\n");
    let mut groups: Vec<&str> = Vec::new();
    for h in hosts {
        if !groups.contains(&h.group.as_str()) {
            groups.push(&h.group);
        }
    }
    let host_entries = groups
        .iter()
        .map(|g| {
            let entries = hosts
                .iter()
                .filter(|h| h.group == *g)
                .map(|h| {
                    format!(
                        "      {}: (...args) => missing({}, {})(...args),",
                        json_ident(&h.name),
                        json_string(g),
                        json_string(&h.name)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!("    {}: {{\n{}\n    }},", json_string(g), entries)
        })
        .collect::<Vec<_>>()
        .join("\n");
    let host_section = if hosts.is_empty() {
        String::new()
    } else {
        [
            "",
            "// Host groups this program declared with `@host(\"…\")`. Each entry is a",
            "// function the module imports, and `provide` replaces one before the module",
            "// is instantiated. A declaration nobody supplied fails saying which it was,",
            "// rather than quietly doing nothing.",
            "const HOSTS = {",
            &host_entries,
            "};",
            NET_HOST,
            CRYPTO_HOST,
            "",
            "function missing(group, name) {",
            "  return () => {",
            "    throw new Error(`no host supplied for @host(\"${group}\") ${name}`);",
            "  };",
            "}",
            "",
            "/// Supply a host group before the module is instantiated.",
            "export function provide(group, functions) {",
            "  HOSTS[group] = Object.assign(HOSTS[group] ?? {}, functions);",
            "}",
            "",
        ]
        .join("\n")
    };

    format!(
        r#"// Generated by kitec. Do not edit.
//
// Kite programs reach the host through a declared boundary rather than an
// ambient runtime, so everything the module can do is visible in this file.

{hosts}
// String constants. A `str` is an index into this table, which is why the
// module needs no linear memory. Concatenation appends, so the table grows.
const STRINGS = [
{table}
];

function intern(s) {{
  const existing = STRINGS.indexOf(s);
  if (existing !== -1) return existing;
  return STRINGS.push(s) - 1;
}}

/// A `str` for an exported function to take.
///
/// A `str` is an index into the table above, not a pointer and not a JavaScript
/// string. Passing a JavaScript string to an export does not fail — the Wasm
/// JS API runs `ToNumber` on it, which gives `NaN`, which becomes index 0 —
/// so the program reads whichever string happens to be first. Anything calling
/// an export with text has to come through here.
export function str(s) {{
  return intern(String(s));
}}

/// The text a `str` stands for, for a value an export returned.
export function text(i) {{
  return STRINGS[i];
}}

// An `int` is an i64, which reaches here as a BigInt.
const showInt = (v) => String(v);

// Floats print so they read back as Kite floats: `1.0`, not `1`.
const showFloat = (v) =>
  Number.isFinite(v) && Number.isInteger(v) ? v.toFixed(1) : String(v);

const showBool = (v) => (v ? "true" : "false");

// ---- rendering ------------------------------------------------------------
//
// A Kite program draws by calling `draw.rect` and `draw.text`, and knows
// nothing else about the host. Everything a layout produces is one of those
// two, which is what lets a DOM renderer and a canvas renderer meet the same
// interface — and what makes it impossible for them to disagree about where
// something went, because neither decides.

const hex = (colour) => '#' + (colour >>> 0).toString(16).padStart(6, '0');
export const FONT = '16px ui-monospace, monospace';

// The default: describe each call. Useful under Node, and the same text the
// bytecode VM writes, so the two backends can be compared without a browser.
// Coordinates print the way Kite prints a float, so this and the bytecode VM
// produce the same text and the differential suite can compare drawing.
export const textRenderer = {{
  rect: (x, y, w, h, colour) =>
    write(
      'rect ' + showFloat(x) + ' ' + showFloat(y) + ' ' +
      showFloat(w) + ' ' + showFloat(h) + ' ' + colour,
    ),
  text: (x, y, body, colour) =>
    write('text ' + showFloat(x) + ' ' + showFloat(y) + ' ' + body + ' ' + colour),
  clip: (x, y, w, h) =>
    write(
      'clip ' + showFloat(x) + ' ' + showFloat(y) + ' ' +
      showFloat(w) + ' ' + showFloat(h),
    ),
  unclip: () => write('unclip'),
}};

// Absolutely-positioned elements under one container. The layout has already
// decided every position, so the container needs no layout of its own.
export function domRenderer(container) {{
  container.style.position = 'relative';

  // A clip becomes a nested element with `overflow: hidden`, and everything
  // drawn until the matching `unclip` goes inside it. Its children are
  // positioned relative to it, so the origin has to be subtracted — which is
  // the whole difference between this and the canvas renderer, where a clip is
  // a path and coordinates never move.
  let host = container;
  let originX = 0;
  let originY = 0;
  const stack = [];

  const place = (el, x, y) => {{
    el.style.position = 'absolute';
    el.style.left = x - originX + 'px';
    el.style.top = y - originY + 'px';
    return el;
  }};
  return {{
    rect: (x, y, w, h, colour) => {{
      const el = place(document.createElement('div'), x, y);
      // A filled rectangle is decoration until something says otherwise, and
      // a screen reader announcing "group" for every box is worse than
      // silence.
      el.setAttribute('aria-hidden', 'true');
      el.style.width = w + 'px';
      el.style.height = h + 'px';
      el.style.background = hex(colour);
      host.appendChild(el);
    }},
    text: (x, y, body, colour) => {{
      const el = place(document.createElement('div'), x, y);
      el.style.color = hex(colour);
      el.style.font = FONT;
      el.style.whiteSpace = 'pre';
      el.textContent = body;
      host.appendChild(el);
    }},
    clip: (x, y, w, h) => {{
      const el = place(document.createElement('div'), x, y);
      el.style.width = w + 'px';
      el.style.height = h + 'px';
      el.style.overflow = 'hidden';
      host.appendChild(el);
      stack.push([host, originX, originY]);
      host = el;
      originX = x;
      originY = y;
    }},
    unclip: () => {{
      const popped = stack.pop();
      if (popped) {{
        host = popped[0];
        originX = popped[1];
        originY = popped[2];
      }}
    }},
  }};
}}

// The same drawing onto a 2D context. Text is drawn from its top-left, which
// is where the layout put it, so the baseline is set rather than assumed.
/// Where a canvas renderer's text is announced.
///
/// A canvas is a picture: everything a program draws into one is invisible to
/// a screen reader, which is the accessibility cost of the canvas path and the
/// reason the DOM renderer is the one to ship first. What closes the gap is a
/// **parallel tree**: the same runs of text, in the same order, in hidden DOM
/// next to the canvas. It is not a full accessibility tree — there are no
/// roles, no focus and no live regions yet — and calling it one would be a
/// claim this does not earn.
let announcer = null;

export function setAnnouncer(element) {{
  announcer = element;
  if (element) element.replaceChildren();
}}

function announce(body) {{
  if (!announcer || body === '') return;
  const line = document.createElement('div');
  line.textContent = body;
  announcer.appendChild(line);
}}

export function canvasRenderer(ctx) {{
  // A clip nests with `save`/`restore`, so an unbalanced `unclip` would
  // restore state a caller never saved. The depth is tracked to refuse that
  // rather than corrupt the context.
  let depth = 0;
  return {{
    rect: (x, y, w, h, colour) => {{
      ctx.fillStyle = hex(colour);
      ctx.fillRect(x, y, w, h);
    }},
    text: (x, y, body, colour) => {{
      announce(body);
      ctx.fillStyle = hex(colour);
      ctx.font = FONT;
      ctx.textBaseline = 'top';
      ctx.fillText(body, x, y);
    }},
    clip: (x, y, w, h) => {{
      ctx.save();
      depth += 1;
      ctx.beginPath();
      ctx.rect(x, y, w, h);
      ctx.clip();
    }},
    unclip: () => {{
      if (depth > 0) {{
        ctx.restore();
        depth -= 1;
      }}
    }},
  }};
}}

// How wide a run of text is. Only the host knows the font, so this is the
// host's answer — and two hosts may legitimately differ, which is what
// different fonts are.
//
// The default is the nominal advance, matching the bytecode VM, so a layout is
// comparable across backends under test. A page that draws installs a real
// measurer and gets numbers that match what it will actually paint.
const NOMINAL_ADVANCE = 8;
export let measure = (body) => [...body].length * NOMINAL_ADVANCE;

export function setMeasure(fn) {{
  measure = fn;
}}

// What one line of text occupies: ascent plus descent plus leading. A canvas
// reports the first two, and the third is what the difference between them and
// the em box amounts to.
export let lineHeight = 16;

export function setLineHeight(v) {{
  lineHeight = v;
}}

/// Measure with a canvas, in the font the renderers draw with. A canvas is
/// used even for the DOM renderer: `measureText` is the same shaping the
/// browser applies to a text node, and it costs no layout.
export function fontMeasure(font) {{
  const ctx = document.createElement('canvas').getContext('2d');
  ctx.font = font;
  return (body) => ctx.measureText(body).width;
}}

/// The font's own line height, from the metrics a canvas reports. Falling back
/// to the nominal value matters: `fontBoundingBox*` is not universal, and a
/// layout that produced `NaN` would place everything at zero.
export function fontLineHeight(font) {{
  const ctx = document.createElement('canvas').getContext('2d');
  ctx.font = font;
  const m = ctx.measureText('Mg');
  const ascent = m.fontBoundingBoxAscent ?? m.actualBoundingBoxAscent;
  const descent = m.fontBoundingBoxDescent ?? m.actualBoundingBoxDescent;
  const height = (ascent ?? 0) + (descent ?? 0);
  return Number.isFinite(height) && height > 0 ? height : 16;
}}

export let renderer = textRenderer;

export function setRenderer(r) {{
  renderer = r;
}}

/// Where output goes. Replace to capture it.
export let write = (line) => console.log(line);

export function setWriter(fn) {{
  write = fn;
}}

function imports() {{
  return {{
{host_spread}    kite: {{
      print_int: (v) => write(showInt(v)),
      print_float: (v) => write(showFloat(v)),
      print_bool: (v) => write(showBool(v)),
      print_str: (i) => write(STRINGS[i]),
      str_concat: (a, b) => intern(STRINGS[a] + STRINGS[b]),
      str_eq: (a, b) => (STRINGS[a] === STRINGS[b] ? 1 : 0),
      // By code point, which is what `<` on JavaScript strings compares and
      // what Rust's `str` ordering compares — so the two backends sort the
      // same way. It is *not* alphabetical order in every language; collation
      // is a table and a locale, and neither belongs in an operator.
      str_compare: (a, b) =>
        STRINGS[a] < STRINGS[b] ? -1n : STRINGS[a] > STRINGS[b] ? 1n : 0n,
      draw_rect: (x, y, w, h, colour) => renderer.rect(x, y, w, h, Number(colour)),
      draw_text: (x, y, i, colour) => renderer.text(x, y, STRINGS[i], Number(colour)),
      draw_clip: (x, y, w, h) => renderer.clip(x, y, w, h),
      draw_unclip: () => renderer.unclip(),
      measure_text: (i) => measure(STRINGS[i]),
      line_height: () => lineHeight,
      // Kite counts characters, JavaScript counts UTF-16 code units, so each
      // of these goes through `[...s]` rather than indexing the string.
      str_slice: (i, from, to) => {{
        const cs = [...STRINGS[i]];
        const a = Math.min(Math.max(Number(from), 0), cs.length);
        const b = Math.min(Math.max(Number(to), a), cs.length);
        return intern(cs.slice(a, b).join(''));
      }},
      str_index_of: (i, n) => {{
        const at = STRINGS[i].indexOf(STRINGS[n]);
        return at < 0 ? -1n : BigInt([...STRINGS[i].slice(0, at)].length);
      }},
      str_trim: (i) => intern(STRINGS[i].trim()),
      // Interpolation shares its formatting with printing, so a value cannot
      // look one way in `io.print(x)` and another in `"\(x)"`.
      str_of_int: (v) => intern(showInt(v)),
      str_of_float: (v) => intern(showFloat(v)),
      str_of_bool: (v) => intern(showBool(v)),
      // Characters, not UTF-16 code units: `[...s]` iterates code points, so
      // an emoji counts once rather than twice.
      str_len: (i) => BigInt([...STRINGS[i]].length),
      // ---- the scheduler ---------------------------------------------------
      //
      // A queue of live tasks is mutable state, and Kite has none, so the
      // scheduler lives here. What crosses the boundary is a resume closure
      // the host cannot look inside: it is handed back through the module's
      // own `kite_poll` export, which is the only thing that can enter it.
      task_spawn: (poll) => {{
        TASKS.push({{ poll, wakeAt: null, parked: false, waitingOnHost: false }});
      }},
      task_wake_at: (ms) => {{
        wakeRequest = Number(ms);
      }},
      task_park: () => {{
        parkRequest = true;
      }},
      task_wait_host: () => {{
        hostWaitRequest = true;
      }},
      time_now: () => BigInt(clock),
    }},
  }};
}}

/// A renderer that records what it was asked to draw, so a frame identical to
/// the last one can be skipped.
///
/// This is the cheap half of damage tracking: it does not find *which*
/// rectangle changed, only whether anything did. That is the half that matters
/// for an application whose model did not change — a key press it ignored, a
/// pointer moving over nothing — and the expensive half needs a scene graph
/// that survives between frames, which is Phase 8's work.
export function recordingRenderer() {{
  const calls = [];
  return {{
    calls,
    rect: (x, y, w, h, colour) => calls.push(['r', x, y, w, h, colour]),
    text: (x, y, body, colour) => calls.push(['t', x, y, body, colour]),
    clip: (x, y, w, h) => calls.push(['c', x, y, w, h]),
    unclip: () => calls.push(['u']),
  }};
}}

/// Replay recorded calls into a real renderer.
export function replay(calls, renderer) {{
  for (const call of calls) {{
    if (call[0] === 'r') renderer.rect(call[1], call[2], call[3], call[4], call[5]);
    else if (call[0] === 't') renderer.text(call[1], call[2], call[3], call[4]);
    else if (call[0] === 'c') renderer.clip(call[1], call[2], call[3], call[4]);
    else renderer.unclip();
  }}
}}

/// Whether two recordings are the same picture.
export function sameFrame(a, b) {{
  if (a === null || b === null || a.length !== b.length) return false;
  for (let i = 0; i < a.length; i += 1) {{
    if (a[i].length !== b[i].length) return false;
    for (let j = 0; j < a[i].length; j += 1) {{
      if (a[i][j] !== b[i][j]) return false;
    }}
  }}
  return true;
}}

// ---- the scheduler --------------------------------------------------------
//
// Round-robin, in spawn order — the same order the bytecode VM polls in, which
// is what lets the two backends be compared at all.
//
// The clock is **virtual**. When every task is waiting on a deadline it jumps
// to the earliest one rather than waiting for it, so a program that sleeps
// costs no real time and two backends running the same program produce the
// same interleaving. A scheduler that raced real timers could not be
// differentially tested, and a UI event loop does not need one: events arrive
// from the host, not from the clock.
const TASKS = [];
let clock = 0;
let wakeRequest = null;
let parkRequest = false;
let hostWaitRequest = false;

export async function drive(exports) {{
  while (TASKS.length > 0) {{
    let polled = false;
    let completed = false;
    for (let i = 0; i < TASKS.length; ) {{
      const task = TASKS[i];
      if (task.parked || task.waitingOnHost || (task.wakeAt !== null && task.wakeAt > clock)) {{
        i += 1;
        continue;
      }}
      polled = true;
      task.wakeAt = null;
      wakeRequest = null;
      parkRequest = false;
      hostWaitRequest = false;
      const done = exports.kite_poll(task.poll) !== 0;
      if (TASKS[i] === task) {{
        task.wakeAt = wakeRequest;
        task.parked = parkRequest;
        task.waitingOnHost = hostWaitRequest;
      }}
      if (done) {{
        TASKS.splice(i, 1);
        completed = true;
      }} else {{
        i += 1;
      }}
    }}
    // A task finishing is what a parked task is waiting for, and may be what a
    // sleeping one wanted too — so a completion wakes everything and lets each
    // decide for itself.
    if (completed) {{
      for (const t of TASKS) {{
        t.parked = false;
        t.wakeAt = null;
      }}
    }}
    if (!polled) {{
      // Everything is waiting. A task waiting on the host — a fetch, a timer
      // the host owns — needs the event loop to run, which is what yielding to
      // a macrotask does. Only then does the virtual clock move.
      if (TASKS.some((t) => t.waitingOnHost)) {{
        await new Promise((resolve) => setTimeout(resolve, 0));
        for (const t of TASKS) t.waitingOnHost = false;
        continue;
      }}
      const next = TASKS.reduce(
        (best, t) => (t.wakeAt !== null && (best === null || t.wakeAt < best) ? t.wakeAt : best),
        null,
      );
      if (next === null || next <= clock) {{
        throw new Error(TASKS.length + ' task(s) can never make progress');
      }}
      clock = next;
    }}
  }}
}}

export async function instantiate(source = {wasm}) {{
  const bytes =
    source instanceof Uint8Array
      ? source
      : new Uint8Array(await (await fetch(source)).arrayBuffer());
  const {{ instance }} = await WebAssembly.instantiate(bytes, imports());
  return instance.exports;
}}

export async function run(source) {{
  const exports = await instantiate(source);
  if (typeof exports.main !== "function") {{
    throw new Error("this module has no `main`");
  }}
  const result = exports.main();
  // `main` returning is not the program ending: a task it started is still
  // the program's work, and dropping it would make `async` silently lossy.
  if (typeof exports.kite_poll === "function") {{
    await drive(exports);
  }}
  return result;
}}

// An application exports `init`, `view` and `update` instead of `main`.
//
// The model never crosses the boundary as data — it is a Wasm reference the
// host holds and hands back, opaque to JavaScript. That is what lets a model
// be any Kite type at all without needing a representation both sides agree
// on, and it is why `update` returns a new model rather than mutating one:
// Kite has no mutable global state to mutate.
//
// `update(model, event, x, y, key)` takes every event through one door. A
// click fills `x` and `y` and leaves `key` empty; a key press fills `key` and
// leaves the position at zero. One signature rather than one per event means a
// new kind of event is a new constant rather than a new export, and a program
// that ignores a kind simply never matches on it.
export const EVENT_CLICK = 0n;
export const EVENT_KEY = 1n;
/// A wheel: `y` carries the distance, `x` the horizontal one.
export const EVENT_WHEEL = 2n;
/// The pointer moved, went down, or came up. One door, as with the rest: a
/// new kind of event is a new constant, and a program that ignores a kind
/// simply never matches on it.
export const EVENT_MOVE = 3n;
export const EVENT_DOWN = 4n;
export const EVENT_UP = 5n;
/// The window was resized: `x` and `y` carry the new size.
export const EVENT_RESIZE = 6n;

export function isApplication(exports) {{
  return ["init", "view", "update"].every((n) => typeof exports[n] === "function");
}}
"#,
        table = table,
        hosts = host_section,
        host_spread = if hosts.is_empty() { "" } else { "    ...HOSTS,\n" },
        wasm = json_string(wasm_path),
    )
}

/// The `net` group, which `std/http` and `std/socket` declare.
///
/// Supplied here rather than left to the page because every environment Kite
/// runs in has `fetch`, and a standard library whose one boundary had to be
/// wired up by hand would not be much of a standard library. A program that
/// wants a different one calls `provide("net", …)` and replaces it.
///
/// A request is a handle rather than a promise: `str` and `int` are what cross
/// the boundary, so the module starts a request, is told to wait for the host,
/// and asks again. Streams — server-sent events and sockets — are the same
/// handle with a queue behind it, which is why they share one table: what
/// changes between them is which browser object fills the queue, not how a
/// program reads it.
const NET_HOST: &str = r#"
if (HOSTS.net) {
  const REQUESTS = [];
  const STREAMS = [];
  const parseHeaders = (text) => {
    const out = {};
    for (const line of String(text).split("\n")) {
      const at = line.indexOf(":");
      if (at > 0) out[line.slice(0, at).trim()] = line.slice(at + 1).trim();
    }
    return out;
  };
  HOSTS.net = {
    fetch_start: (method, url, body, headers) => {
      const request = { state: 0, status: 0, body: "", error: "", headers: null };
      const id = REQUESTS.push(request) - 1;
      const init = { method: STRINGS[method], headers: parseHeaders(STRINGS[headers]) };
      if (STRINGS[body] !== "") init.body = STRINGS[body];
      fetch(STRINGS[url], init)
        .then(async (response) => {
          request.status = response.status;
          request.headers = response.headers;
          request.body = await response.text();
          request.state = 1;
        })
        .catch((e) => {
          request.error = String(e && e.message ? e.message : e);
          request.state = 2;
        });
      return BigInt(id);
    },
    fetch_state: (id) => BigInt(REQUESTS[Number(id)].state),
    fetch_status: (id) => BigInt(REQUESTS[Number(id)].status),
    fetch_body: (id) => intern(REQUESTS[Number(id)].body),
    fetch_header: (id, name) => {
      const headers = REQUESTS[Number(id)].headers;
      return intern(headers ? headers.get(STRINGS[name]) ?? "" : "");
    },
    fetch_error: (id) => intern(REQUESTS[Number(id)].error),

    // ---- server-sent events, which are EventSource ----
    //
    // `onerror` fires on every dropped connection, and EventSource reconnects
    // by itself — so only a source it has given up on (readyState 2) is a
    // failure the program is told about.
    sse_open: (url, names) => {
      const s = { state: 0, queue: [], taken: { name: "", id: "" }, source: null };
      const id = STREAMS.push(s) - 1;
      if (typeof EventSource === "undefined") {
        s.state = 2;
        return BigInt(id);
      }
      const source = new EventSource(STRINGS[url]);
      s.source = source;
      s.take = (e) => {
        s.queue.push({ name: e.type || "message", id: e.lastEventId || "", data: e.data ?? "" });
      };
      source.onopen = () => { s.state = 1; };
      source.onmessage = s.take;
      // Registered before anything can arrive, which is the whole reason the
      // names are given at open.
      for (const name of STRINGS[names].split("\n")) {
        if (name !== "") source.addEventListener(name, s.take);
      }
      source.onerror = () => { if (source.readyState === 2) s.state = 2; };
      return BigInt(id);
    },
    sse_state: (id) => BigInt(STREAMS[Number(id)].state),
    sse_pending: (id) => BigInt(STREAMS[Number(id)].queue.length),
    sse_next: (id) => {
      const s = STREAMS[Number(id)];
      const e = s.queue.shift();
      if (e === undefined) {
        s.taken = { name: "", id: "" };
        return intern("");
      }
      s.taken = { name: e.name, id: e.id };
      return intern(e.data);
    },
    sse_event_name: (id) => intern(STREAMS[Number(id)].taken.name),
    sse_event_id: (id) => intern(STREAMS[Number(id)].taken.id),
    sse_listen: (id, name) => {
      const s = STREAMS[Number(id)];
      if (s.source) s.source.addEventListener(STRINGS[name], s.take);
      return 1n;
    },
    sse_close: (id) => {
      const s = STREAMS[Number(id)];
      if (s.source) s.source.close();
      s.state = 3;
      return 1n;
    },

    // ---- sockets, which are WebSocket ----
    //
    // Text frames only: a `str` is what crosses this boundary, and handing a
    // program an empty string where a binary frame arrived would be inventing
    // a message that was never sent.
    socket_open: (url) => {
      const s = { state: 0, queue: [], error: "", socket: null };
      const id = STREAMS.push(s) - 1;
      if (typeof WebSocket === "undefined") {
        s.state = 2;
        s.error = "this host has no WebSocket";
        return BigInt(id);
      }
      let socket;
      try {
        socket = new WebSocket(STRINGS[url]);
      } catch (e) {
        s.state = 2;
        s.error = String(e && e.message ? e.message : e);
        return BigInt(id);
      }
      s.socket = socket;
      socket.onopen = () => { s.state = 1; };
      socket.onmessage = (e) => { if (typeof e.data === "string") s.queue.push(e.data); };
      socket.onerror = () => {
        if (s.state !== 3) {
          s.state = 2;
          if (s.error === "") s.error = "the connection failed";
        }
      };
      socket.onclose = () => { if (s.state !== 2) s.state = 3; };
      return BigInt(id);
    },
    socket_state: (id) => BigInt(STREAMS[Number(id)].state),
    socket_pending: (id) => BigInt(STREAMS[Number(id)].queue.length),
    socket_next: (id) => {
      const s = STREAMS[Number(id)];
      const message = s.queue.shift();
      return intern(message === undefined ? "" : message);
    },
    socket_send: (id, message) => {
      const s = STREAMS[Number(id)];
      if (s.state !== 1 || !s.socket) return 0n;
      s.socket.send(STRINGS[message]);
      return 1n;
    },
    socket_error: (id) => intern(STREAMS[Number(id)].error),
    socket_close: (id) => {
      const s = STREAMS[Number(id)];
      if (s.socket) s.socket.close();
      s.state = 3;
      return 1n;
    },
  };
}
"#;

/// The `crypto` group, which `std/crypto` declares.
///
/// Bindings, not implementations: every one of these is the host's own
/// primitive. WebCrypto is asynchronous, so a digest starts and is polled —
/// what crosses the boundary is a handle and hex text, because that is what
/// crosses it at all.
const CRYPTO_HOST: &str = r#"
if (HOSTS.crypto) {
  const WORK = [];
  const subtle = globalThis.crypto && globalThis.crypto.subtle;
  const hex = (buffer) =>
    [...new Uint8Array(buffer)].map((b) => b.toString(16).padStart(2, "0")).join("");
  const unhex = (text) =>
    new Uint8Array((String(text).match(/../g) ?? []).map((b) => parseInt(b, 16)));
  const start = (promise) => {
    const work = { state: 0, result: "", error: "" };
    const id = WORK.push(work) - 1;
    promise
      .then((value) => {
        work.result = value;
        work.state = 1;
      })
      .catch((e) => {
        work.error = String(e && e.message ? e.message : e);
        work.state = 2;
      });
    return BigInt(id);
  };
  const bytes = (text) => new TextEncoder().encode(text);
  HOSTS.crypto = {
    random_hex: (count) => {
      const out = new Uint8Array(Number(count));
      globalThis.crypto.getRandomValues(out);
      return intern(hex(out.buffer));
    },
    digest_start: (algorithm, text) =>
      start(subtle.digest(STRINGS[algorithm], bytes(STRINGS[text])).then(hex)),
    hmac_start: (algorithm, key, text) =>
      start(
        subtle
          .importKey("raw", bytes(STRINGS[key]), { name: "HMAC", hash: STRINGS[algorithm] }, false, [
            "sign",
          ])
          .then((k) => subtle.sign("HMAC", k, bytes(STRINGS[text])))
          .then(hex),
      ),
    derive_start: (password, salt, iterations) =>
      start(
        subtle
          .importKey("raw", bytes(STRINGS[password]), "PBKDF2", false, ["deriveBits"])
          .then((k) =>
            subtle.deriveBits(
              {
                name: "PBKDF2",
                salt: unhex(STRINGS[salt]),
                iterations: Number(iterations),
                hash: "SHA-256",
              },
              k,
              256,
            ),
          )
          .then(hex),
      ),
    work_state: (id) => BigInt(WORK[Number(id)].state),
    work_result: (id) => intern(WORK[Number(id)].result),
    work_error: (id) => intern(WORK[Number(id)].error),
    // Same time whichever way it goes: every byte is compared, and the length
    // is folded in rather than returned early on.
    constant_time_equal: (a, b) => {
      const x = STRINGS[a];
      const y = STRINGS[b];
      let diff = x.length ^ y.length;
      for (let i = 0; i < Math.max(x.length, y.length); i += 1) {
        diff |= (x.charCodeAt(i % x.length) || 0) ^ (y.charCodeAt(i % y.length) || 0);
      }
      return diff === 0 ? 1 : 0;
    },
  };
}
"#;

/// A JavaScript object key, quoted only when it has to be.
fn json_ident(name: &str) -> String {
    let plain = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        && !name.starts_with(|c: char| c.is_ascii_digit());
    if plain {
        name.to_string()
    } else {
        json_string(name)
    }
}

/// A page that runs the module, with a control for which renderer draws.
///
/// The same compiled module backs all three: the program calls `draw.rect` and
/// `draw.text` and cannot tell where they went. Being able to switch between
/// them in one page is the clearest evidence that neither renderer is deciding
/// anything about layout.
pub fn generate_page(title: &str) -> String {
    format!(
        r#"<!doctype html>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ margin: 0; background: #0b0d10; color: #c9d1dc;
         font: 14px ui-monospace, SFMono-Regular, Menlo, monospace; }}
  header {{ display: flex; gap: 12px; align-items: center; padding: 10px 14px;
            border-bottom: 1px solid #1f232b; }}
  button {{ font: inherit; color: inherit; background: #1a1e25; cursor: pointer;
            border: 1px solid #2a2f3a; border-radius: 4px; padding: 4px 10px; }}
  button[aria-pressed="true"] {{ background: #3b82f6; border-color: #3b82f6; color: #fff; }}
  main {{ padding: 14px; }}
  #stage {{ width: 640px; height: 360px; position: relative; }}
  pre {{ margin: 0; white-space: pre-wrap; }}
  /* The parallel tree for the canvas renderer: read by a screen reader,
     invisible to everyone else. `display: none` would hide it from both. */
  #announcer {{ position: absolute; width: 1px; height: 1px; overflow: hidden;
                clip-path: inset(50%); white-space: nowrap; }}
  /* Where typing goes when the canvas is drawing. A canvas cannot hold a
     caret, so the text lands in a real input positioned under the pointer and
     kept invisible — the same trick every canvas editor uses. */
  #typing {{ position: absolute; opacity: 0; pointer-events: none; width: 1px; }}
</style>

<header>
  <strong>{title}</strong>
  <button id="dom" aria-pressed="true">DOM</button>
  <button id="canvas" aria-pressed="false">canvas</button>
  <button id="text" aria-pressed="false">text</button>
</header>

<main>
  <div id="stage"></div>
  <div id="announcer" role="region" aria-live="polite" aria-label="drawing"></div>
  <input id="typing" aria-hidden="true" tabindex="-1">
</main>

<script type="module">
  import {{ instantiate, setRenderer, setWriter, isApplication, setMeasure,
            setLineHeight, fontMeasure, fontLineHeight, FONT, setAnnouncer,
            EVENT_CLICK, EVENT_KEY, EVENT_WHEEL, EVENT_MOVE, EVENT_DOWN,
            EVENT_UP, EVENT_RESIZE, str, recordingRenderer, replay, sameFrame,
            domRenderer, canvasRenderer, textRenderer }} from "./app.js";

  // Measure in the font that will be drawn, before anything is laid out.
  setMeasure(fontMeasure(FONT));
  setLineHeight(fontLineHeight(FONT));

  const stage = document.getElementById("stage");
  const announcer = document.getElementById("announcer");
  const typing = document.getElementById("typing");
  let currentRenderer = textRenderer;
  const buttons = {{
    dom: document.getElementById("dom"),
    canvas: document.getElementById("canvas"),
    text: document.getElementById("text"),
  }};

  // One instance for the life of the page. A program that exports `init`,
  // `view` and `update` keeps its model inside the module — the host holds a
  // reference and hands it back, opaque to JavaScript — so instantiating again
  // would throw the model away.
  const exports = await instantiate("./app.wasm");
  const interactive = isApplication(exports);
  let model = interactive ? exports.init() : null;
  let mode = "dom";


  function mount(which) {{
    stage.replaceChildren();
    setAnnouncer(which === "canvas" ? announcer : null);
    if (which === "text") {{
      // The text renderer writes rather than draws, so it needs somewhere to
      // write to before the frame is replayed.
    }}
    if (which === "canvas") {{
      const canvas = document.createElement("canvas");
      const scale = window.devicePixelRatio || 1;
      canvas.width = 640 * scale;
      canvas.height = 360 * scale;
      canvas.style.width = "640px";
      canvas.style.height = "360px";
      stage.appendChild(canvas);
      const ctx = canvas.getContext("2d");
      ctx.scale(scale, scale);
      currentRenderer = canvasRenderer(ctx);
    }} else if (which === "text") {{
      const pre = document.createElement("pre");
      stage.appendChild(pre);
      setWriter((line) => {{ pre.textContent += line + "\n"; }});
      currentRenderer = textRenderer;
    }} else {{
      currentRenderer = domRenderer(stage);
    }}
  }}

  // A frame is recorded before it is painted, and an identical one is not
  // painted at all. That is the half of damage tracking a model that did not
  // change needs — a key press the program ignored, a pointer moving over
  // nothing — and it costs one comparison.
  let lastFrame = null;

  function draw(force) {{
    const recorder = recordingRenderer();
    setRenderer(recorder);
    if (interactive) {{
      exports.view(model);
    }} else {{
      exports.main();
    }}
    if (!force && sameFrame(lastFrame, recorder.calls)) return;
    lastFrame = recorder.calls;
    mount(mode);
    replay(recorder.calls, currentRenderer);
  }}

  function show(which) {{
    mode = which;
    for (const [name, button] of Object.entries(buttons)) {{
      button.setAttribute("aria-pressed", String(name === which));
    }}
    draw(true);
  }}

  // An event becomes a new model, and the new model replaces the old. Nothing
  // else changes: the program has no way to reach the page, and the page has
  // no way to reach inside the model.
  function send(kind, x, y, key) {{
    if (!interactive) return;
    // `key` is interned rather than passed as a JavaScript string: a `str` is
    // an index into the module's table, and handing an export a string quietly
    // becomes index 0.
    model = exports.update(model, kind, x, y, str(key));
    draw(false);
  }}

  const at = (e) => {{
    const box = stage.getBoundingClientRect();
    return [e.clientX - box.left, e.clientY - box.top];
  }};

  stage.addEventListener("click", (e) => {{
    const [x, y] = at(e);
    send(EVENT_CLICK, x, y, "");
    // Typing goes to a real input placed where the pointer is: a canvas
    // cannot hold a caret, and an invisible input is how every canvas editor
    // handles this. It also brings the on-screen keyboard up on a phone.
    if (mode === "canvas") {{
      typing.style.left = x + "px";
      typing.style.top = y + "px";
      typing.focus({{ preventScroll: true }});
    }}
  }});

  // Pointer events, all through the same door as everything else.
  stage.addEventListener("pointermove", (e) => {{
    const [x, y] = at(e);
    send(EVENT_MOVE, x, y, "");
  }});
  stage.addEventListener("pointerdown", (e) => {{
    const [x, y] = at(e);
    send(EVENT_DOWN, x, y, "");
  }});
  stage.addEventListener("pointerup", (e) => {{
    const [x, y] = at(e);
    send(EVENT_UP, x, y, "");
  }});

  // Text typed into the hidden input arrives one character at a time, which
  // is the same shape a key press has. An IME's composition arrives here too,
  // once it is committed.
  typing.addEventListener("input", () => {{
    for (const character of typing.value) {{
      send(EVENT_KEY, 0, 0, character);
    }}
    typing.value = "";
  }});

  window.addEventListener("resize", () => {{
    const box = stage.getBoundingClientRect();
    send(EVENT_RESIZE, box.width, box.height, "");
  }});

  // Keys go to the document rather than the stage: a div is not focusable, and
  // making it so would put a focus ring around the whole application.
  document.addEventListener("keydown", (e) => {{
    if (!interactive || e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.target !== document.body) return;
    // A key the program acts on should not also scroll the page. Which keys
    // those are is the program's business, so this asks by comparing the model
    // it gives back — an application that ignores the key is left alone.
    const before = model;
    send(EVENT_KEY, 0, 0, e.key);
    if (model !== before) e.preventDefault();
  }});

  stage.addEventListener("wheel", (e) => {{
    if (!interactive) return;
    const before = model;
    send(EVENT_WHEEL, e.deltaX, e.deltaY, "");
    if (model !== before) e.preventDefault();
  }}, {{ passive: false }});

  for (const [name, button] of Object.entries(buttons)) {{
    button.addEventListener("click", () => show(name));
  }}
  show("dom");
</script>
"#,
        title = title
    )
}

/// Encode a Rust string as a JavaScript string literal.
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Escape control characters and the line separators that are legal
            // in JSON but not in a JavaScript string literal.
            c if (c as u32) < 0x20 || c == '\u{2028}' || c == '\u{2029}' => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strings_are_escaped_for_javascript() {
        assert_eq!(json_string("a\"b"), r#""a\"b""#);
        assert_eq!(json_string("a\nb"), r#""a\nb""#);
        assert_eq!(json_string("a\\b"), r#""a\\b""#);
        assert_eq!(json_string("tab\there"), r#""tab\there""#);
    }

    /// U+2028 and U+2029 are valid JSON but terminate a JavaScript string
    /// literal, which is a classic way to generate broken glue.
    #[test]
    fn line_separators_are_escaped() {
        assert_eq!(json_string("a\u{2028}b"), "\"a\\u2028b\"");
        assert_eq!(json_string("a\u{2029}b"), "\"a\\u2029b\"");
    }

    #[test]
    fn the_glue_embeds_every_string_constant() {
        let g = generate_glue(&["hello".into(), "world".into()], "app.wasm");
        assert!(g.contains(r#""hello""#));
        assert!(g.contains(r#""world""#));
        assert!(g.contains(r#""app.wasm""#));
        assert!(g.contains("export async function run"));
    }
}
