//! JavaScript glue generation.
//!
//! There is no standardised way for Wasm to call a Web API without JavaScript
//! glue — no Web IDL bindings proposal has landed, and none is imminent. Kite
//! therefore declares the host boundary explicitly and *generates* the glue
//! from that declaration, so the two cannot drift apart.
//!
//! The generated module is deliberately tiny and has no dependencies.

/// The JavaScript module that instantiates a compiled Kite program.
pub fn generate_glue(strings: &[String], wasm_path: &str) -> String {
    let table = strings
        .iter()
        .map(|s| format!("  {},", json_string(s)))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// Generated by kitec. Do not edit.
//
// Kite programs reach the host through a declared boundary rather than an
// ambient runtime, so everything the module can do is visible in this file.

// String constants. A `str` is an index into this table, which is why the
// module needs no linear memory. Concatenation appends, so the table grows.
const STRINGS = [
{table}
];

function intern(s) {{
  const existing = STRINGS.indexOf(s);
  if (existing !== -1) return existing;
  return STRINGS.push(s) - 1;
}}

// An `int` is an i64, which reaches here as a BigInt.
const showInt = (v) => String(v);

// Floats print so they read back as Kite floats: `1.0`, not `1`.
const showFloat = (v) =>
  Number.isFinite(v) && Number.isInteger(v) ? v.toFixed(1) : String(v);

const showBool = (v) => (v ? "true" : "false");

// ---- rendering ------------------------------------------------------------
//
// A Kite program draws by calling `draw.rect` and `draw.text`, and knows
// nothing else about the host. Everything a layout produces is one of those
// two, which is what lets a DOM renderer and a canvas renderer meet the same
// interface — and what makes it impossible for them to disagree about where
// something went, because neither decides.

const hex = (colour) => '#' + (colour >>> 0).toString(16).padStart(6, '0');
const FONT = '16px ui-monospace, monospace';

// The default: describe each call. Useful under Node, and the same text the
// bytecode VM writes, so the two backends can be compared without a browser.
// Coordinates print the way Kite prints a float, so this and the bytecode VM
// produce the same text and the differential suite can compare drawing.
export const textRenderer = {{
  rect: (x, y, w, h, colour) =>
    write(
      'rect ' + showFloat(x) + ' ' + showFloat(y) + ' ' +
      showFloat(w) + ' ' + showFloat(h) + ' ' + colour,
    ),
  text: (x, y, body, colour) =>
    write('text ' + showFloat(x) + ' ' + showFloat(y) + ' ' + body + ' ' + colour),
}};

// Absolutely-positioned elements under one container. The layout has already
// decided every position, so the container needs no layout of its own.
export function domRenderer(container) {{
  container.style.position = 'relative';
  const place = (el, x, y) => {{
    el.style.position = 'absolute';
    el.style.left = x + 'px';
    el.style.top = y + 'px';
    return el;
  }};
  return {{
    rect: (x, y, w, h, colour) => {{
      const el = place(document.createElement('div'), x, y);
      el.style.width = w + 'px';
      el.style.height = h + 'px';
      el.style.background = hex(colour);
      container.appendChild(el);
    }},
    text: (x, y, body, colour) => {{
      const el = place(document.createElement('div'), x, y);
      el.style.color = hex(colour);
      el.style.font = FONT;
      el.style.whiteSpace = 'pre';
      el.textContent = body;
      container.appendChild(el);
    }},
  }};
}}

// The same drawing onto a 2D context. Text is drawn from its top-left, which
// is where the layout put it, so the baseline is set rather than assumed.
export function canvasRenderer(ctx) {{
  return {{
    rect: (x, y, w, h, colour) => {{
      ctx.fillStyle = hex(colour);
      ctx.fillRect(x, y, w, h);
    }},
    text: (x, y, body, colour) => {{
      ctx.fillStyle = hex(colour);
      ctx.font = FONT;
      ctx.textBaseline = 'top';
      ctx.fillText(body, x, y);
    }},
  }};
}}

export let renderer = textRenderer;

export function setRenderer(r) {{
  renderer = r;
}}

/// Where output goes. Replace to capture it.
export let write = (line) => console.log(line);

export function setWriter(fn) {{
  write = fn;
}}

function imports() {{
  return {{
    kite: {{
      print_int: (v) => write(showInt(v)),
      print_float: (v) => write(showFloat(v)),
      print_bool: (v) => write(showBool(v)),
      print_str: (i) => write(STRINGS[i]),
      str_concat: (a, b) => intern(STRINGS[a] + STRINGS[b]),
      str_eq: (a, b) => (STRINGS[a] === STRINGS[b] ? 1 : 0),
      draw_rect: (x, y, w, h, colour) => renderer.rect(x, y, w, h, Number(colour)),
      draw_text: (x, y, i, colour) => renderer.text(x, y, STRINGS[i], Number(colour)),
      // Interpolation shares its formatting with printing, so a value cannot
      // look one way in `io.print(x)` and another in `"\(x)"`.
      str_of_int: (v) => intern(showInt(v)),
      str_of_float: (v) => intern(showFloat(v)),
      str_of_bool: (v) => intern(showBool(v)),
      // Characters, not UTF-16 code units: `[...s]` iterates code points, so
      // an emoji counts once rather than twice.
      str_len: (i) => BigInt([...STRINGS[i]].length),
    }},
  }};
}}

export async function instantiate(source = {wasm}) {{
  const bytes =
    source instanceof Uint8Array
      ? source
      : new Uint8Array(await (await fetch(source)).arrayBuffer());
  const {{ instance }} = await WebAssembly.instantiate(bytes, imports());
  return instance.exports;
}}

export async function run(source) {{
  const exports = await instantiate(source);
  if (typeof exports.main !== "function") {{
    throw new Error("this module has no `main`");
  }}
  return exports.main();
}}
"#,
        table = table,
        wasm = json_string(wasm_path),
    )
}

/// A page that runs the module, with a control for which renderer draws.
///
/// The same compiled module backs all three: the program calls `draw.rect` and
/// `draw.text` and cannot tell where they went. Being able to switch between
/// them in one page is the clearest evidence that neither renderer is deciding
/// anything about layout.
pub fn generate_page(title: &str) -> String {
    format!(
        r#"<!doctype html>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ margin: 0; background: #0b0d10; color: #c9d1dc;
         font: 14px ui-monospace, SFMono-Regular, Menlo, monospace; }}
  header {{ display: flex; gap: 12px; align-items: center; padding: 10px 14px;
            border-bottom: 1px solid #1f232b; }}
  button {{ font: inherit; color: inherit; background: #1a1e25; cursor: pointer;
            border: 1px solid #2a2f3a; border-radius: 4px; padding: 4px 10px; }}
  button[aria-pressed="true"] {{ background: #3b82f6; border-color: #3b82f6; color: #fff; }}
  main {{ padding: 14px; }}
  #stage {{ width: 640px; height: 360px; }}
  pre {{ margin: 0; white-space: pre-wrap; }}
</style>

<header>
  <strong>{title}</strong>
  <button id="dom" aria-pressed="true">DOM</button>
  <button id="canvas" aria-pressed="false">canvas</button>
  <button id="text" aria-pressed="false">text</button>
</header>

<main>
  <div id="stage"></div>
</main>

<script type="module">
  import {{ instantiate, setRenderer, setWriter,
            domRenderer, canvasRenderer, textRenderer }} from "./app.js";

  const stage = document.getElementById("stage");
  const buttons = {{
    dom: document.getElementById("dom"),
    canvas: document.getElementById("canvas"),
    text: document.getElementById("text"),
  }};

  // The module is instantiated once per draw: `main` runs to completion and
  // draws as it goes, so redrawing means running it again. A program that
  // redrew on its own would need a frame loop, which arrives with events.
  async function show(which) {{
    for (const [name, button] of Object.entries(buttons)) {{
      button.setAttribute("aria-pressed", String(name === which));
    }}
    stage.replaceChildren();

    if (which === "canvas") {{
      const canvas = document.createElement("canvas");
      const scale = window.devicePixelRatio || 1;
      canvas.width = 640 * scale;
      canvas.height = 360 * scale;
      canvas.style.width = "640px";
      canvas.style.height = "360px";
      stage.appendChild(canvas);
      const ctx = canvas.getContext("2d");
      ctx.scale(scale, scale);
      setRenderer(canvasRenderer(ctx));
    }} else if (which === "text") {{
      const pre = document.createElement("pre");
      stage.appendChild(pre);
      setWriter((line) => {{ pre.textContent += line + "\n"; }});
      setRenderer(textRenderer);
    }} else {{
      setRenderer(domRenderer(stage));
    }}

    const exports = await instantiate("./app.wasm");
    exports.main();
  }}

  for (const [name, button] of Object.entries(buttons)) {{
    button.addEventListener("click", () => show(name));
  }}
  show("dom");
</script>
"#,
        title = title
    )
}

/// Encode a Rust string as a JavaScript string literal.
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Escape control characters and the line separators that are legal
            // in JSON but not in a JavaScript string literal.
            c if (c as u32) < 0x20 || c == '\u{2028}' || c == '\u{2029}' => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strings_are_escaped_for_javascript() {
        assert_eq!(json_string("a\"b"), r#""a\"b""#);
        assert_eq!(json_string("a\nb"), r#""a\nb""#);
        assert_eq!(json_string("a\\b"), r#""a\\b""#);
        assert_eq!(json_string("tab\there"), r#""tab\there""#);
    }

    /// U+2028 and U+2029 are valid JSON but terminate a JavaScript string
    /// literal, which is a classic way to generate broken glue.
    #[test]
    fn line_separators_are_escaped() {
        assert_eq!(json_string("a\u{2028}b"), "\"a\\u2028b\"");
        assert_eq!(json_string("a\u{2029}b"), "\"a\\u2029b\"");
    }

    #[test]
    fn the_glue_embeds_every_string_constant() {
        let g = generate_glue(&["hello".into(), "world".into()], "app.wasm");
        assert!(g.contains(r#""hello""#));
        assert!(g.contains(r#""world""#));
        assert!(g.contains(r#""app.wasm""#));
        assert!(g.contains("export async function run"));
    }
}
