//! The server adapter, generated.
//!
//! `std/http` declares ten host functions for listening — open, poll, take,
//! read, answer, close. This writes the JavaScript that answers them for a
//! runtime that has sockets: Node, Deno or Bun.
//!
//! It is a separate file from the glue rather than another group inside it,
//! and that is the point. The glue is what a *page* loads, and a page cannot
//! listen on a port; a server is a different program with a different entry
//! point, and pretending otherwise would put `node:http` in the import graph
//! of every compiled Kite program that draws a rectangle.
//!
//! The adapter reaches the module through the glue's own `provide("net", …)`,
//! which already exists for exactly this: a host group is an object a host
//! fills in before the module is instantiated. Nothing here needed a change to
//! the boundary.
//!
//! **WASI is not this.** `wasi:http/incoming-handler` is the other
//! implementation the boundary was shaped for, and it is not written: it is a
//! component-model export and `kitec` emits a core module. Saying so is worth
//! more than a stub that looks like an answer.

/// Whether a program declared the listening half of `std/http`.
///
/// A program that only fetches gets no adapter, because it would import
/// `node:http` to never use it.
pub fn listens(hosts: &[crate::HostImport]) -> bool {
    hosts.iter().any(|h| h.group == "net" && h.name == "serve_open")
}

/// The Node adapter for one compiled module.
///
/// `entry` is the exported function to run — an ordinary `main`, which is
/// where a program calls `http.open` and `http.run`.
pub fn generate_server(wasm_path: &str) -> String {
    format!(
        r#"// Generated by kitec. Do not edit.
//
// The server adapter: it answers the `net` host group's listening half for a
// runtime that has sockets. Run it with `node serve.mjs`.
//
// Nothing here decides anything about the program. A request is queued, the
// program takes it when a task asks for one, and the answer goes back to the
// socket that is still waiting — so the Kite side sees the same "take, then
// answer" shape it sees for every other boundary, and the asynchrony stays on
// this side of it.

import {{ readFile }} from "node:fs/promises";
import {{ createServer }} from "node:http";
import {{ run, provide, setWriter }} from "./app.js";

// One entry per listening socket. A handle is an index, as everywhere else on
// this boundary: nothing but numbers and text crosses it.
const SERVERS = [];
// One entry per request that arrived and has not been answered. Kept apart
// from the queue so that answering a request the program took, and taking the
// next one, are two independent things.
//
// A `Map` rather than an array, because entries have to *leave*. An answered
// request holds its body, its headers and the live `res`, and an array index
// is never reclaimed — so a server that had served a million requests was
// still holding all million of them. Deleting on answer is what makes the
// memory proportional to what is in flight rather than to uptime.
const REQUESTS = new Map();
let NEXT_REQUEST = 0;

// The largest body this adapter will accumulate before refusing, in bytes.
//
// The body arrives in chunks and was concatenated with no ceiling, so an
// unauthenticated client streaming `Transfer-Encoding: chunked` chose how much
// memory the process used, and the answer was "all of it". A limit belongs
// here rather than in the program, because the program does not see the
// request until the body is already whole.
const MAX_BODY = 8 * 1024 * 1024;

// A missing handle is a bug in the program, not a reason to end the process:
// indexing `undefined` throws, and an uncaught throw unwinds through the Wasm
// frame and takes the server with it.
const requestOf = (handle) => REQUESTS.get(Number(handle));

const headerLines = (headers) =>
  Object.entries(headers)
    .map(([name, value]) => name + ": " + (Array.isArray(value) ? value.join(", ") : value))
    .join("\n");

// A header is `name: value`, one per line — the shape everything crosses this
// boundary in, because only text does.
//
// The splitting is what makes it dangerous, and the danger is worth stating.
// Node refuses a header *value* containing a newline (`ERR_INVALID_CHAR`);
// splitting on newlines first turns what it would have refused into two
// well-formed headers, so this encoding hands a program's mistake straight to
// the wire and defeats a check the runtime already had. A program that
// interpolates anything a request said into a header string is one newline
// away from setting a cookie somebody else chose.
//
// So a name is held to the RFC 7230 token set and a value to "no CR, LF or
// NUL", and anything else is dropped rather than sent. Dropped, not escaped:
// there is no escaping that keeps the meaning, and a header nobody can read is
// better than a header somebody else wrote.
const TOKEN = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
const parseHeaders = (lines) => {{
  const out = {{}};
  // `\r?\n`, so a CR cannot ride along on the end of a value.
  for (const line of String(lines).split(/\r?\n/)) {{
    const at = line.indexOf(":");
    if (at <= 0) continue;
    const name = line.slice(0, at).trim();
    const value = line.slice(at + 1).trim();
    if (!TOKEN.test(name)) continue;
    if (/[\r\n\0]/.test(value)) continue;
    out[name] = value;
  }}
  return out;
}};

provide("net", {{
  serve_open: (port) => {{
    const state = {{ queue: [], error: "", port: -1, server: null }};
    const id = SERVERS.push(state) - 1;
    try {{
      state.server = createServer((req, res) => {{
        // The chunks are kept as `Buffer`s and decoded once at the end, which
        // is two fixes in one shape.
        //
        // `body += chunk` decoded each chunk on its own, and a chunk boundary
        // is a position in a byte stream, not in a text: a character whose
        // UTF-8 bytes straddled two `data` events became two replacement
        // characters. That needed no attacker — any non-ASCII body large
        // enough to arrive in two pieces was quietly corrupted before the
        // program ever saw it.
        //
        // And `body.length` on the decoded string counts UTF-16 code units,
        // which is not what `MAX_BODY` says it counts. Three-byte characters
        // count one apiece, so the 8 MiB ceiling admitted about 24 MiB off
        // the wire. `chunk.length` on a `Buffer` is bytes, which is the unit
        // the limit is written in.
        let chunks = [];
        let received = 0;
        let refused = false;
        req.on("data", (chunk) => {{
          if (refused) return;
          received += chunk.length;
          if (received > MAX_BODY) {{
            // Refused here rather than handed on: the program is never told
            // about this request, so there is nothing for it to answer, and
            // the memory goes back now rather than when it gets around to it.
            refused = true;
            chunks = [];
            res.writeHead(413, {{ "content-type": "text/plain; charset=utf-8" }});
            res.end("request body too large\n");
            req.destroy();
            return;
          }}
          chunks.push(chunk);
        }});
        req.on("end", () => {{
          if (refused) return;
          const body = Buffer.concat(chunks).toString("utf8");
          // The socket is held open until the program answers. A server that
          // replied before its handler ran would be a different program.
          const handle = NEXT_REQUEST++;
          REQUESTS.set(handle, {{
            method: req.method,
            path: req.url,
            body,
            headers: headerLines(req.headers),
            res,
            answered: false,
          }});
          state.queue.push(handle);
        }});
      }});
      state.server.on("error", (e) => {{
        state.error = String(e && e.message ? e.message : e);
      }});
      state.server.listen(Number(port));
      state.server.on("listening", () => {{
        state.port = state.server.address().port;
      }});
    }} catch (e) {{
      state.error = String(e && e.message ? e.message : e);
      return -1n;
    }}
    return BigInt(id);
  }},

  // -1 until the socket is actually bound, and -1 again once it is shut. The
  // Kite side waits on this rather than assuming, because `listen` is not
  // instant and a port reported before there was one would be wrong rather
  // than late.
  serve_port: (id) => {{
    const state = SERVERS[Number(id)];
    if (!state || !state.server || !state.server.listening) return -1n;
    const address = state.server.address();
    return BigInt(address ? address.port : -1);
  }},

  serve_pending: (id) => BigInt(SERVERS[Number(id)].queue.length),

  serve_next: (id) => {{
    const handle = SERVERS[Number(id)].queue.shift();
    return handle === undefined ? -1n : BigInt(handle);
  }},

  // Plain JavaScript strings in both directions. A declared host is called
  // with strings the module has already converted, and what it returns is
  // converted on the way back — `str` and `text` are the *public* API's
  // helpers, for callers outside the module, and wrapping a host value in
  // them hands the conversion an object it cannot read.
  serve_method: (handle) => (requestOf(handle) ? requestOf(handle).method : ""),
  serve_path: (handle) => (requestOf(handle) ? requestOf(handle).path : ""),
  serve_body: (handle) => (requestOf(handle) ? requestOf(handle).body : ""),
  serve_headers: (handle) => (requestOf(handle) ? requestOf(handle).headers : ""),

  serve_respond: (handle, status, body, headers) => {{
    const request = requestOf(handle);
    // Answering twice is a bug in the program, not a thing to do quietly: the
    // second answer goes nowhere and this says so.
    if (!request || request.answered) return 0n;
    request.answered = true;
    const fields = parseHeaders(headers);
    if (fields["content-type"] === undefined && fields["Content-Type"] === undefined) {{
      fields["content-type"] = "text/plain; charset=utf-8";
    }}
    // A header Node still refuses is a bug in the program, not a reason to end
    // the process: `writeHead` throws, and an uncaught throw here unwinds
    // through the Wasm frame and takes the server with it.
    try {{
      request.res.writeHead(Number(status), fields);
    }} catch (e) {{
      request.res.writeHead(500, {{ "content-type": "text/plain; charset=utf-8" }});
      request.res.end("the handler produced a header this host will not send\n");
      REQUESTS.delete(Number(handle));
      return 0n;
    }}
    request.res.end(body);
    // Answered, so the body, the headers and the socket can go. Holding them
    // for the life of the process is what made an ordinary stream of requests
    // a memory leak.
    REQUESTS.delete(Number(handle));
    return 1n;
  }},

  serve_error: (id) => {{
    const state = SERVERS[Number(id)];
    return state ? state.error : "no such server";
  }},

  serve_close: (id) => {{
    const state = SERVERS[Number(id)];
    if (state && state.server) {{
      state.server.close();
      state.port = -1;
    }}
    return 1n;
  }},
}});

// `io.print` goes to stdout here rather than to a page.
setWriter((line) => process.stdout.write(line + "\n"));

await run(new Uint8Array(await readFile(new URL("./{wasm_path}", import.meta.url))));
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn host(name: &str) -> crate::HostImport {
        crate::HostImport {
            group: "net".to_string(),
            name: name.to_string(),
            params: 1,
            returns: true,
        }
    }

    #[test]
    fn only_a_program_that_listens_gets_an_adapter() {
        assert!(!listens(&[]));
        assert!(!listens(&[host("fetch_start")]));
        assert!(listens(&[host("fetch_start"), host("serve_open")]));
    }

    /// Every function `std/http` declares for listening has to be answered
    /// here, or the module fails to instantiate with a name nobody can place.
    #[test]
    fn the_adapter_answers_every_declaration() {
        let source = generate_server("app.wasm");
        for name in [
            "serve_open",
            "serve_port",
            "serve_pending",
            "serve_next",
            "serve_method",
            "serve_path",
            "serve_body",
            "serve_headers",
            "serve_respond",
            "serve_error",
            "serve_close",
        ] {
            assert!(
                source.contains(&format!("{}:", name)),
                "the adapter never answers `{}`",
                name
            );
        }
    }
}
