// Generated by kitec. Do not edit.
//
// The typed door into a Kite module. Every `pub fn` is here with its
// conversions already applied: an `int` is a BigInt on the wire, and a
// `str` may be an index into a table this file interns into and reads
// back out of. A caller sees ordinary JavaScript values.

import { instantiate, str, text } from "./app.js";

let module = null;

/// Load the module. Call this once before anything else here.
export async function load(source = "app.wasm") {
  module = await instantiate(source);
  return module;
}

const ready = () => {
  if (module === null) {
    throw new Error("call `await load()` before calling into the module");
  }
  return module;
};

export function prelude.contains(s, needle) {
  return (ready().prelude.contains(str(s), str(needle))) !== 0;
}

export function prelude.lower(text) {
  return text(ready().prelude.lower(str(text)));
}

export function prelude.pad_start(text, width, with_2) {
  return text(ready().prelude.pad_start(str(text), width, str(with_2)));
}

// Left out, because these take or answer with a type JavaScript has no
// representation for yet: js.global, js.get, js.set, js.at, js.length, js.call1, js.call2, js.is_nothing, js.of_str, js.as_str, js.as_num, js.as_int, js.str_or, dom.find, dom.find_all, dom.create, dom.set_text, dom.attribute, dom.add_class, dom.append, dom.on, dom.event_value.
// The module still exports them; describing them wrongly would be worse
// than not describing them.
