[package]
name = "kite-hir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Typed high-level IR for Kite"

[dependencies]
kite-span.workspace = true
kite-types.workspace = true
kite-resolve.workspace = true
