[package]
name = "kite-lexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Tokeniser for the Kite language"

[dependencies]
kite-span.workspace = true
kite-diag.workspace = true
unicode-ident = "1.0.24"
