//! How a Kite float is written as text.
//!
//! Three backends print floats, and they printed them three ways at the edges:
//! the bytecode VM and the native runtime used Rust's `{}`, and the Wasm glue
//! used JavaScript's `Number#toString`. The same program printed `inf` or
//! `Infinity`, `-0.0` or `0.0`, `0.0000001` or `1e-7`, and a 327-character
//! decimal or `5e-324`, depending on where it ran.
//!
//! This crate is the rule for the two runtimes written in Rust — the VM and
//! `kite-rt` — so that they cannot drift from each other, and the glue's
//! `showFloat` is its transcription into JavaScript. Section 4.2 of the
//! specification states it:
//!
//! * `NaN` is `NaN`; the infinities are `inf` and `-inf`.
//! * Zero is `0.0`, and negative zero `-0.0`: it is a different value, and
//!   `1.0 / -0.0` says so.
//! * A whole number below `1e21` in magnitude is its exact digits and `.0`, so
//!   it reads back as a float rather than an `int`: `3.0`, `1e20` as
//!   `100000000000000000000.0`, `2^63` as `9223372036854775808.0`.
//! * Anything else is the shortest decimal that reads back as the same
//!   `f64`, laid out as ECMAScript lays out `Number#toString`: plainly from
//!   `1e-7` up to `1e21`, and in exponent form outside that — `1e-7`,
//!   `1.5e-7`, `1e+21`, `1.7976931348623157e+308`. Every one of those is also
//!   a Kite float literal.

/// `v` as Kite writes it — the text of `io.print(v)` and of `"\(v)"`.
pub fn float_text(v: f64) -> String {
    if v.is_nan() {
        return "NaN".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 { "inf" } else { "-inf" }.to_string();
    }
    if v == 0.0 {
        return if v.is_sign_negative() { "-0.0" } else { "0.0" }.to_string();
    }
    // A whole number is written in full, which is `toFixed(1)` in JavaScript
    // and `{:.1}` here: both give the exact decimal value, not the shortest.
    if v.fract() == 0.0 && v.abs() < 1e21 {
        return format!("{:.1}", v);
    }
    let (sign, v) = if v < 0.0 { ("-", -v) } else { ("", v) };
    // `{:e}` gives the shortest digits that round-trip, as `d.ddde<x>`.
    let scientific = format!("{:e}", v);
    let (mantissa, exponent) = scientific
        .split_once('e')
        .expect("`{:e}` always writes an exponent");
    let exponent: i32 = exponent.parse().expect("the exponent is an integer");
    let digits: String = mantissa.chars().filter(|c| *c != '.').collect();
    let k = digits.len() as i32;
    // ECMAScript's `n`: the value is `0.d1d2…dk × 10^n`.
    let n = exponent + 1;
    let body = if k <= n && n <= 21 {
        // A whole number, which the branch above already wrote; kept so the
        // layout is ECMAScript's in full.
        format!("{}{}.0", digits, "0".repeat((n - k) as usize))
    } else if 0 < n && n <= 21 {
        let (whole, fraction) = digits.split_at(n as usize);
        format!("{}.{}", whole, fraction)
    } else if -6 < n && n <= 0 {
        format!("0.{}{}", "0".repeat((-n) as usize), digits)
    } else {
        let e = n - 1;
        let mantissa = if k == 1 {
            digits
        } else {
            format!("{}.{}", &digits[..1], &digits[1..])
        };
        format!("{}e{}{}", mantissa, if e < 0 { '-' } else { '+' }, e.abs())
    };
    format!("{}{}", sign, body)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every edge the three backends once disagreed about, with the text the
    /// Wasm glue's `showFloat` writes for it — generated by running that
    /// function under Node, so this table is the cross-check between the two
    /// implementations of the rule.
    #[test]
    fn floats_are_written_the_way_the_glue_writes_them() {
        let table: &[(f64, &str)] = &[
            (0.1 + 0.2, "0.30000000000000004"),
            (1.0 / 3.0, "0.3333333333333333"),
            (1e21, "1e+21"),
            (1e20, "100000000000000000000.0"),
            (123456789012345680000.0, "123456789012345683968.0"),
            (1e-7, "1e-7"),
            (0.000001, "0.000001"),
            (f64::INFINITY, "inf"),
            (f64::NEG_INFINITY, "-inf"),
            (f64::NAN, "NaN"),
            (-0.0, "-0.0"),
            (0.0, "0.0"),
            (2.0, "2.0"),
            (-2.5, "-2.5"),
            (5e-324, "5e-324"),
            (1.7976931348623157e308, "1.7976931348623157e+308"),
            (1e16, "10000000000000000.0"),
            (1e15 + 0.5, "1000000000000000.5"),
            (9007199254740993.0, "9007199254740992.0"),
            (1.5e-7, "1.5e-7"),
            (123e-20, "1.23e-18"),
            (1e100, "1e+100"),
            (0.5, "0.5"),
            (100.0, "100.0"),
            (9223372036854775808.0, "9223372036854775808.0"),
            (-9223372036854775808.0, "-9223372036854775808.0"),
            (-1e21, "-1e+21"),
            (12345.678, "12345.678"),
            (0.00001, "0.00001"),
            (0.1, "0.1"),
            (25e-8, "2.5e-7"),
            (-1e-7, "-1e-7"),
            (1.0000000000000002, "1.0000000000000002"),
            (4.35, "4.35"),
            (0.000123, "0.000123"),
            (1e-300, "1e-300"),
            (2.2250738585072014e-308, "2.2250738585072014e-308"),
        ];
        for (v, want) in table {
            assert_eq!(float_text(*v), *want, "{:?}", v);
        }
    }
}
