[package]
name = "kite-mir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "SSA mid-level IR for Kite"

[dependencies]
kite-span.workspace = true
kite-hir.workspace = true
kite-types.workspace = true
