[package]
name = "kite-resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Name resolution and scoping for Kite"

[dependencies]
kite-span.workspace = true
kite-diag.workspace = true
kite-ast.workspace = true
