[package]
name = "kite-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Type checker for Kite"

[dependencies]
kite-span.workspace = true
kite-diag.workspace = true
kite-ast.workspace = true
kite-resolve.workspace = true
