[package]
name = "kite-codegen-kbc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Kite bytecode code generator"

[dependencies]
kite-mir.workspace = true
kite-hir.workspace = true

[dev-dependencies]
kite-span.workspace = true
kite-diag.workspace = true
kite-lexer.workspace = true
kite-parser.workspace = true
kite-resolve.workspace = true
kite-types.workspace = true
